services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  #     REDIS_ADDR: redis:6379
  #     REDIS_PASSWORD: ""  # customize if needed
  #     # Add other env vars as required, e.g. REDIS_PASSWORD, JWT_SECRET, etc.
  #   ports:
  #     - "8080:8080"  # Map to your Go app's port
  #   networks:
  #     - app-network

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    # networks:
    #   - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    # networks:
    #   - app-network

volumes:
  postgres_data:
  redis_data:

# networks:
#   app-network:
